apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: onlinebookstore-products
  name: onlinebookstore-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlinebookstore-products
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: onlinebookstore-products
    spec:
      containers:
      - image: kishore101/onlinebookstore.products:SNAPSHOT-0.0.2
        name: onlinebookstore-products-fv9zj
        resources: {}
status: {}
